version: '3'
services:
  aplicacao:
    build:
      context: ./aplicacao
    container_name: container-aplicacao
    networks:
      - minha-rede
    ports:
      - "8081:8081"
  api:
    build:
      context: ./api
    container_name: container-api
    depends_on:
      - banco-dados
    networks:
      - minha-rede
    ports:
      - "3000:3000"
  banco-dados:
    build:
      context: ./banco_dados
    container_name: container-banco-dados
    networks:
      - minha-rede
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
networks:
  minha-rede:
volumes:
  db_data: