version: '3'
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - '3306:3306'